//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by UISKin.rc
//
#define IDB_HORIZONTAL_SCROLLBAR_SPAN   1026
#define IDB_HORIZONTAL_SCROLLBAR_RIGHTARROW 1027
#define IDB_HORIZONTAL_SCROLLBAR_THUMB  1028
#define IDB_HORIZONTAL_SCROLLBAR_SLIDER_CENTER 1029
#define IDB_HORIZONTAL_SCROLLBAR_SLIDER_RIGHT 1030
#define IDB_HORIZONTAL_SCROLLBAR_LEFTARROW 1031
#define IDB_HORIZONTAL_SCROLLBAR_SLIDER_LEFT 1032
#define IDB_VERTICLE_SCROLLBAR_SPAN     1033
#define IDB_VERTICLE_SCROLLBAR_DOWNARROW 1034
#define IDB_VERTICLE_SCROLLBAR_UPARROW  1035
#define IDB_VERTICLE_SCROLLBAR_SLIDER_BOTTOM 1036
#define IDB_VERTICLE_SCROLLBAR_SLIDER_CENTER 1037
#define IDB_VERTICLE_SCROLLBAR_THUMB    1038
#define IDB_VERTICLE_SCROLLBAR_SLIDER_TOP 1039

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1040
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
